name: Run tests, build sdist and wheel and publish to PyPI and TestPyPI

on: push

jobs:
  test:
    name: Run unit tests with pytest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install pytest
      run: >-
        python -m pip install --user pytest
    - name: Runs tests
      run: python -m pytest -v tests
  build:
    name: Build sdist and wheel
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install pypa/build
      run: >-
        python -m pip install --user build hatchling
    - name: Build a binary wheel and a source tarball
      run: >-
        python -m build --no-isolation
    - uses: actions/upload-artifact@v3
      with:
        name: sdist-and-wheel
        path: dist/
  publish:
    name: Publish to PyPI and TestPyPI
    runs-on: ubuntu-latest
    needs: build
    environment: PyPI release
    if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags')
    steps:
    - uses: actions/checkout@master
    - uses: actions/download-artifact@v3
      with:
        name: sdist-and-wheel
        path: dist/
    - name: Publish distribution to Test PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        skip_existing: true
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
    - name: Publish distribution to PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
